### PR TITLE
Add PySide2 support

### PR DESCRIPTION
**Pull request by robbmcleod**
Adds support for PySide2, as Qt seems to be supporting it now quite strongly.

Also changes default to `PyQt5`, which  you may want to edit out.

### CODE REVIEW

**Comment by hmeine** [comment]
Although I believe it should better have been a separate change / commit, I think changing the default is also sensible at this point in time.

Thanks for the contribution!

**Comment by hmeine** [comment]
@robbmcleod Could you maybe update the ChangeLog as well?

**Comment by robbmcleod** [comment]
Looks like you did it?

**Comment by hmeine** [comment]
Yes, thanks again.

**Pull request merged**
