### PR TITLE
Pyqt5 support added

### PR DESCRIPTION
**Pull request by rhoef**
Added support for PyQt5.

Extension is compiling on Linux. Qt changed the way how headers are organized --> troubles on OSX could not be resolved so far (Frameworks are not *nix-like).

Added a setup.cfg to set sip options. PyQt5 does not support pyqtconfig, Use ```PyQt5.QtCore.PYQT_CONFIGURATION``` to get sip options. Remove option ```extra_requires```. This option is setuptools only. 

Added ```compat.py``` for unit testing to take care of API changes in Qt5.

Here's the result:
```
nosetests test
..............................................
----------------------------------------------------------------------
Ran 46 tests in 4.038s

OK
```

### CODE REVIEW

**Comment by rhoef** [comment]
I changed the default back to PyQt. If I understand the code correct, it does not matter as long as qimage2ndarray does not import a qt-binding first. 

The old setup[_sip].py tried to find the include paths and sip configuration automatically. Since the class ```PyQt4.pyqtconfig.Configuration()``` is legacy and not present in PyQt5 I choose the standard Python way to define include and library directories (always found PyQt4 first).  But after all it's up to you how to do this.

**Comment by vilim** [comment]
Hello!
I find this module very useful and tried the Qt5 branch (I have only PyQt5 installed), but there is a strange issue: the code works with the debugger attached, (pydev with PyCharm), but throws the following error when run without the debugger.
```
 import qimage2ndarray
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qimage2ndarray/__init__.py", line 4, in <module>
    from .dynqt import QtGui as _qt
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qimage2ndarray/dynqt.py", line 4, in <module>
    QtGui = qt.QtGui
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qimage2ndarray/qt_driver.py", line 128, in __getattr__
    return self.importMod(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qimage2ndarray/qt_driver.py", line 123, in importMod
    qt = __import__('%s.%s' % (self._drv, mod))
ImportError: No module named PyQt4.QtGui
```

**Comment by rhoef** [comment]
Hi,
if qimage2ndarray finds PyQt5 already imported than it's using PyQt5, otherwise it defaults to PyQt4. So try out this:

```
import PyQt5
import qimage2ndarray
````

If there are  there any PyQt4 import statements through other libraries imports might get messed up to.
Matplotlib is such a library. Here you have to set the backend to "qt5agg" either in the matplotlibrc file or a the beginning of your script.

**Comment by hmeine** [comment]
It is a pity that PyQt5 and PyQt4 cannot be easily installed side-by-side in MacPorts.  Otherwise, I would have worked on this much earlier.  I would like to get this integrated, yet I still need to ensure that it does not break anything for other users.
qimage2ndarray already has a mechanism to switch between different Qt wrappers (PySide and PythonQt are also supported), and one of the ways (that could be recommended due to its simplicity) to select one is to import the bindings before qimage2ndarray, as suggested above.

**Comment by vilim** [comment]
Thank you very much for the quick replies! Reversing the order of the imports solves the problem for me.

**Comment by hmeine** [comment]
Closing, as this was integrated (except for most of the formatting changes).

**Comment by rhoef** [comment]
It's "Höfler", thanks!

**Pull request closed without merging**
